### ISSUE TITLE
Race condition in utils/factory:ssh_connect

### ISSUE THREAD

**Issue by yottatsa** [tomerfiliba-org/rpyc#135]
I've found out that simultaneous `rpyc.classic.ssh_connect` calls from different instances could possibly lead to race condition in https://github.com/tomerfiliba/rpyc/blob/master/rpyc/utils/factory.py#L159 .

Due to non-atomic operations of port discovery and port bind it could be possible to connect to another tunnel. `ssh` only warns you about port has been already used:

```
bind: Address already in use
channel_setup_fwd_listener: cannot listen to port: 2222
```

Since `ssh` does not accept `0` as a bind port, I have no idea how to fix it easy.

**Comment by orivej** [comment]
Starting ssh with `-oExitOnForwardFailure=yes` sidestaps the race condition because then ssh exits if the port is already bound. After that its exit can be noted (altough I'm not sure on the best way to differentiate this exit reason from other ones) and port acquisition restarted.

**Comment by yottatsa** [comment]
Perfect!
