### ISSUE TITLE
Using rpyc for remote testing

### ISSUE THREAD

**Issue by Corvan** [tomerfiliba-org/rpyc#377]
Hey, 

I just wanted to let you know, I found rpyc to be very useful for a use case of mine and share what I was using it for with you https://punkt.de/en/blog/2020/remote-testing.html maybe someone else will find this approach useful as well.

Thank you for helping me out with the library's existence and the zero-deploy functionality 😉.

Lars

**Comment by comrumino** [comment]
Thanks for the love!

**Comment by filip-komarzyniec** [comment]
Hey! The link redirects to the 404 error. Is the blog post available somewhere else? 

I have found the library recently and it seems to suit my need almost perfectly with the remote testing capabilities. I'd love to read someone else's approach to that matter as well, cheers!
