### ISSUE TITLE
add rpyc to conda-forge repository

### ISSUE THREAD

**Issue by mtsolmn** [tomerfiliba-org/rpyc#403]
Hi,

I was curious if there was any objections or opinions about adding the package to conda-forge. It is currently published on a private conda channel `prometeia` but it would be beneficial to have it on an official repo. Thanks.

**Comment by comrumino** [comment]
Seems like a good idea to me
* multi-language projects would benefit from rpyc being a `conda-forge` package as well
* there isn't much overhead beyond the initial conda recipe, supporting scripts and CI config
If you already did the work to host the package privately, then most of the hard work is done. Let me email Tomer and hopefully we have a quick turn around here.

I'll keep you apprised! Thanks for contributing!

**Comment by comrumino** [comment]
For my own future reference, the documentation on [contributing packages](https://conda-forge.org/docs/maintainer/adding_pkgs.html)

**Comment by comrumino** [comment]
@mtsolmn Tomer created an organization and transferred the rpyc repository to it. I started following the [step-by-step instructions](https://conda-forge.org/docs/maintainer/adding_pkgs.html#step-by-step-instructions) for conda-forge. So, now we have an [official staged-recipes repository](https://github.com/tomerfiliba-org/staged-recipes).

Would you be so kind to make a PR to [tomerfiliba-org/staged-recipes](https://github.com/tomerfiliba-org/staged-recipes) with the recipes you've been using for your private conda channel? It would shorten the turnaround time to making rpyc available as a conda-forge package.

Thanks again!

**Comment by mtsolmn** [comment]
@comrumino, I haven't actually written the recipes myself, but there is a version published on conda by an Italian company Prometeia `conda install -c prometeia rpyc`. The feedstock for this doesn't seem to be publicly available (not found at https://github.com/prometeia). I am, however, happy to help you get this up and running. I will make a PR within the next day with what I have for testing.

**Comment by mtsolmn** [comment]
@comrumino can you please add a new branch on https://github.com/tomerfiliba-org/staged-recipes for me to make a PR on, thanks!

**Comment by comrumino** [comment]
Thanks! I created the a branch named [rpyc](https://github.com/tomerfiliba-org/staged-recipes/tree/rpyc).

**Comment by mtsolmn** [comment]
> Thanks! I created the a branch named [rpyc](https://github.com/tomerfiliba-org/staged-recipes/tree/rpyc).

Great! I just made a PR https://github.com/tomerfiliba-org/staged-recipes/pull/1

That should be a good starting point. If you accept it and then make another pull request onto the master branch of conda-forge/stage-recipes https://github.com/conda-forge/staged-recipes, it will start the CI build checks and we can test whether the builds are successful before pinging the admins to merge.

**Comment by mtsolmn** [comment]
@comrumino hey, another update -- it's now live! I got a little impatient (trying to get my own project published) and finished pushing it to conda-forge. The feedstock for maintaining it is here: https://github.com/conda-forge/rpyc-feedstock

If you are unfamiliar with the process of maintaining projects on conda-forge, there is a repo _package name_-feedstock for each package published. Anyone listed as a maintainer in the recipe gets automatically added as an admin for the repo. For the initial _staged-recipes_ PR https://github.com/conda-forge/staged-recipes/pull/12589#event-3743390721 to get merged, each listed maintainer has to comment that they are okay being listed. I didn't want to hold up the process, so you aren't currently listed.

If you are happy to be listed (and if you want me to add Tomer or anyone else), I can push your ID to the list and rebuild -- the CI will automatically give you permissions on the rebuild.

**Comment by comrumino** [comment]
Thanks! Done and I am added to the feedstock.
