### ISSUE TITLE
Pickle Errors when passing LogRecord objects with exc_info from remote to local

### ISSUE THREAD

**Issue by Callek** [tomerfiliba-org/rpyc#410]
Describe the issue briefly here, including:

I don't have a minimized testcase that is suitable for the public atm, but essentially I do the following:

Local side: attach a log handler that expects to receive logRecords in a batch format (List) from Remote and emit them
Local Side: Instantiate and attach a log handler (code exists on remote, and attached on remote) that takes the locally created loghandler as a first arg

Remote then does multiple logging calls, including at least one with `exc_info=True` from inside an exception. 
Remote pushes the List of LogRecords to the local handler.

RPyC then does a bit of back and forth trying to `HANDLE_PICKLE` which it can't do for an `exc_info` object because it contains a `traceback` which can't be pickled.

- expected result versus actual result

Expected a List of LogRecord objects that I can use locally:
Actual Results: EOFError traceback chain due to pickle error

##### Environment

- rpyc version
4.1.5
- python version
3.7.9
- operating system
Fedora32 (local) ; CentOS7 (remote)

I am aware that vinegar is used in passing exceptions from remote to local in isolation, I think my ideal here is some way to use that for LogRecord objects while pickling an array....

(I'll work on getting a minimized testcase for you...)

**Comment by comrumino** [comment]
Since `LogRecord` contains the `traceback` object, there is a limit to what can be pickled/unpickled due to frames containing references to globals and locals. We wouldn't wan't a snapshot of the entire process state to be sent across the network.

```
import rpyc
import unittest
import sys
import logging


class MyService(rpyc.Service):

    def exposed_create_record(self):
        try:
            raise IOError("does this work")
        except Exception:
            factory = logging.getLogRecordFactory()
            exc_info = sys.exc_info()
            record = factory('rpyc', logging.INFO, 'dummy pathname', 31, "record msg", None, exc_info)
            return record


class TestRemoteRecord(unittest.TestCase):
    def setUp(self):
        self.server = rpyc.utils.server.OneShotServer(MyService, protocol_config={'allow_pickle': True}, port=0)
        self.server.logger.quiet = False
        self.server._start_in_thread()
        self.conn = rpyc.connect("localhost", port=self.server.port)

    def tearDown(self):
        self.conn.close()

    def test_remote_dataclass(self):
        remote_dataclass = self.conn.root.create_record()
        obtained_dataclass = rpyc.classic.obtain(remote_dataclass)


if __name__ == "__main__":
    unittest.main()
```

My first instinct would be to write a class that inherits `LogRecord` and defines [pickling class instructions](https://docs.python.org/3/library/pickle.html#pickling-class-instances). If desired, you could use vinegar to serialize data.
