### ISSUE TITLE
add recursive directory/file checksum mismatch check between two different address spaces

### ISSUE THREAD

**Issue by Elyash** [tomerfiliba-org/rpyc#413]
Notice the following code sample:
```python
import my_module

rpyc.classic.upload_module(my_module)
rpyc.classic.upload_module(my_module)
...
```

Although `my_module` never changed, it takes a lot of time for `rpyc` to upload the same module (with the same md5) twice.
I will suggest improving the `upload_file` method, so before uploading the file, it will calculate the md5 of the `local_file` and the `remote_file` and will do nothing if they are equal.

**Comment by comrumino** [comment]
I increased the chunk size used in classic to the increase transfer rate. Verifying that modules are equivalent in the local and remote address spaces is a separate concern from `upload_module`. A function that recursively compares the directories within two different address space would preferable---there would be the potential for reuse outside of modules.

**Comment by comrumino** [comment]
I'm not convinced there is a measurable amount of value added. Users could write such a function using Python libraries. RPyC primary function is to operate in a transparent fashion. So, I'm marking this as won't fix for now.
