### ISSUE TITLE
Connect to server using hostname.

### ISSUE THREAD

**Issue by goalie1998** [tomerfiliba-org/rpyc#428]
I am trying to make a custom server on docker that I can connect to using it's name instead of IP address. Is there a way to do this?

The client config as such does not work when I use the container's name, but does when I use the container's IP address.
```
t = ThreadedServer(MyService, hostname="NAME", port=12345, protocol_config={'allow_all_attrs': True})
t.start()
```

**Comment by comrumino** [comment]
It is possible. I regularly do so using the docker containers as [configured](https://github.com/tomerfiliba-org/rpyc/tree/master/docker).
