### ISSUE TITLE
Blocked trying to call client callback from another thread

### ISSUE THREAD

**Issue by IdeaMogul** [tomerfiliba-org/rpyc#437]
Describe the issue briefly here, including:

I have a use-case where I would like the client to send a callback to the server, and for an arbitrary thread on the server side to be able to call that callback. Every attempt to call this callback on the server side from a thread that is not the thread handling the connection blocks indefinitely.

- Minimal code sample
```python
import threading
import rpyc
import time

class Service(rpyc.Service):

    callback = None

    def exposed_set_callback(self, callback):
        print("[server] Setting callback")
        self.callback = callback

SERVICE_INSTANCE = Service()

def hello():
    print("Hello!")

def start_server():
    print("[server] starting server")
    t = rpyc.ThreadedServer(SERVICE_INSTANCE, port=4567)
    t.start()

def start_client():
    print("[client] starting client" )
    conn = rpyc.connect("localhost", 4567)
    print("[client] client connected" )
    conn.root.set_callback(hello)

def access_callback_on_server():
    while not SERVICE_INSTANCE.callback:
        print("[access] callback not set yet")
        time.sleep(1)
    print("[access] calling" )
    SERVICE_INSTANCE.callback()
    print("[access] returned")


if __name__ == "__main__":
    server_thread = threading.Thread(target=start_server)
    client_thread = threading.Thread(target=start_client)
    access_thread = threading.Thread(target=access_callback_on_server)

    server_thread.start()
    client_thread.start()
    access_thread.start()
    server_thread.join()
```
- expected result:
Access thread successfully returns, printing "Hello!" to the console.

- Actual result:
Access thread never returns from attempting to invoke the callback.

##### Environment

- rpyc version
5.0.1
- python version
3.8.5
- operating system
MacOS 11.2, Ubuntu 20.04.1 LTS

Thanks in advance for any help!

**Comment by gschaffner** [comment]
Hi! This is because your client is not running a server to listen for requests for it to execute the callback. This will work if you add `conn_server = rpyc.BgServingThread(conn)` to `start_client`. Alternatively, you can run a blocking callback server on `client_thread` with `conn.serve_all()` in `start_client`.
