### ISSUE TITLE
Expose disable zlib compression switch

### ISSUE THREAD

**Issue by sobieh** [tomerfiliba-org/rpyc#438]
Hi, im using the newest 5.x version on python 3.8 and after some investigation of my performance issues i found out that there is a default zlib compression enabled for all the packets  bigger than hardcoded THRESHOLD.

I was testing sending bigger (500mb) files with classic.upload/classic.download over local thread server and the results were:
compressed: ~11 MB/s
uncompressed: ~211 MB/s

Would you guys be so kind to expose the compression switch a little bit especially to the CLASSIC version ?
There is literally no way to disable it without modding the library guts or writing own Channel and Server.
Maybe there is some magical way i'm not aware of  ? :/

Thanks.

**Comment by comrumino** [comment]
You can disable compression like so I believe.
```
import rpyc
conn=rpyc.connect('127.0.0.1', port=18812)
conn.root._conn._channel.compress = False
```
Some notes that may help you other others in the future:
1. "It is not possible to create truly immutable Python objects."  per _The Python Library Reference, Release 3.9.2_ under _29.6.5 Frozen instances_
2. Netrefs will tell you whether or not an object is a proxy to an object that exists in a remote address space.
3. By 1 and 3, you should be able to dynamically modify any default values you need on remote.

Of course, there is the question of how the design and documentation could be  improved to make this more obvious. I hope I helped!
