### ISSUE TITLE
[Suggestion] Passing registrar argument to the method connect_by_service()

### ISSUE THREAD

**Issue by thomas-brandeho** [tomerfiliba-org/rpyc#443]
Hello,

I've been using the method `connect_by_service` a lot, which is really useful, but I just run into a limitation with it.

The method make a call to `discover()` to find all the services known for the given name.

But it will always use the default Registrar, where I would like to be able to specify by IP where I should make the discover().
Of course I can reproduce manually the behavior of connect_by_service() with a custom method in my project and add this functionnality, but I didn't see anything that would cause problem by adding this to the library.

Thanks for reading my suggestion, and for all the great work with this very useful library, I love it.

**Comment by comrumino** [comment]
Thanks for requesting this enhancement! You can always use the install the latest commit via pip's VCS project support, like so `pip install git+https://github.com/tomerfiliba-org/rpyc.git`.

Pull-requests are always welcome too and they have the added benefit of giving credit where credit is due :1st_place_medal:
