### ISSUE TITLE
ThreadedServers and Async requests

### ISSUE THREAD

**Issue by RobMeades** [tomerfiliba-org/rpyc#447]
You'll likely need a simple example before this can be answered but, since that will take a little while to generate, I though I'd describe my issue first so that any obvious misunderstandings of mine can be corrected.

I am using RPyC in a test system where a controller PC runs asynchronous operations on multiple [currently 2] agent PCs.  The agents run a `ThreadedServer`, the controller connects to them and makes an `async_` request into each agent, expecting them to do stuff at their own sweet rate (nothing else is running on the agents)  The controller calls `poll_all()` for 5 seconds on each agent, round-robin style, and checks the `ready` property of the `async_result_object` to see if they're done.

What I'm finding is that the agents execute really slowly quite a lot of the time, for instance taking several 10's of seconds to iterate over a list (26 elements) of objects (each containing 9 entries) that it is checking as part of its asynchronous workload.  Since nothing else is executing on the agent machines I'd expected them to zip through this but maybe I've misunderstood how the background `async_` task on the controller and the `ThreadedServer` on the agents interact and how the priorities of both threads are set.

Any pointers would be greatly appreciated.  Now I'll go generate the simple example.

##### Environment

- rpyc 5.0.1
- python version 3.8.5
- operating system Windows 10 Pro 18363

**Comment by RobMeades** [comment]
S'OK, figured it out in the shower this morning; the `async_` call in question is passing an array containing dictionaries to the agent, which are of course all passed by reference and so poor RPyC is thrashing itself to death asking the controller for each element on every iteration of the loop. Doing a `deepcopy()` of that array on arrival at the agent makes everything lightning fast.

Sorry for bothering you; hopefully this issues will guide those less versed in Pythonism, like me, as to what's going on under the hood.

RPyC rocks :-).

**Comment by comrumino** [comment]
I'm glad you figured it out! I've had a lot of positive things going on lately both professionally and personally. I'll have more bandwidth once I wrap up my UW PCE cert for software development and design essentials in the next couple of months. The design portion next quarter will hopefully help me make higher quality contributions and responses :)
