### ISSUE TITLE
RPyC type(netref)

### ISSUE THREAD

**Issue by jacobfeder** [tomerfiliba-org/rpyc#450]
I'm having trouble using RPyC with some external libraries due to the fact that type(client_obj) returns netref. E.g. if client_obj is from a module that internally uses type() or isinstance(), a lot of these internal methods break. Is there any way to have netref objects emulate the remote object with the type() / isinstance() calls?

**Comment by Jongy** [comment]
`isinstance` is emulated by RPyC (by `BaseNetref.__instancecheck__`). So if `a` is a netref of type `list`, `isintance(a, list)` will work; while `type(a) is list` won't work. Therefore, for RPyC-compatible code, you should avoid using `type` for type checks.

AFAIK `type` can not be overriden by normal means (well, you can override it by setting `builtin.type` but there's not slot that lets you override its behavior on a per-class basis)

**Comment by comrumino** [comment]
@jacobfeder shadowing/dyamic-modification of builtins such as type would be more head-ache that it is worth. isinstance the correct choice as suggested by @Jongy . Feel free to reopen if you have follow up questions.

@Jongy thanks for the help doing triage.
