### ISSUE TITLE
Problems with class AsyncResult when using self._is_ready.wait() in wait function wait

### ISSUE THREAD

**Issue by achrafka** [tomerfiliba-org/rpyc#462]
Hello guys 
I'm trying to use this great package in a project and i found out that there were a several problems with a new implementations in a class AsyncResult when using is_set() an inbuilt method of the Event class of the threading module on a variable _is_ready so it could communicate with other threads

```
self._is_ready.is_set() = Event()
```

**Comment by Jongy** [comment]
@achrafka could you please provide more details? Either a short snippet that reproduces the issue you're seeing, or a traceback, etc.

**Comment by achrafka** [comment]
yes sure ! well to be more precise the problem is in the function def wait in the async_.py file i noticed that you are using an if statement `if self._conn.serve(self._ttl):` and waiting for the completion call by `self._is_ready.wait()` and as you know the wait method blocks the thread until an internal flag is true for the event if the internal flag is true and that is my case the thread still waiting for another thread to call set() that it is never called ... now for the traceback i'm using a large project that makes a number of scenarios such as making calls and so on and we are using rpyc so if i try to make a call (using twinkle that is linked to freeswitch and the app is registered in rpyc ) i got error from logs that says :
`Traceback (1) =========#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.6/dist-packages/rpyc/core/protocol.py", line 324, in _dispatch_request#012    res = self._HANDLERS[handler](self, *args)#012  File "/usr/l
ocal/lib/python3.6/dist-packages/rpyc/core/protocol.py", line 608, in _handle_getattr#012    return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)#012  File "/usr/local/lib/python3.6/dist-packages/rpyc/core/pr
otocol.py", line 536, in _access_attr#012    return accessor(obj, name, *args)#012AttributeError: 'ASDService' object has no attribute 'close'`

so if i change the if statement in the `def wait(self):` :
`if self._conn.serve(self._ttl):
          self._is_ready.wait()`

simply to  :
`self._conn.serve(self._ttl)`

the call will proceed and everything works fine

**Comment by wumb0** [comment]
Can you provide a minimal test case so we can reproduce the issue? 
Interesting that's causing you problems. I remember I put that wait in there for a reason... I think I was getting timeouts from it re-entering the function with no response. If the serve function returns true that means a response was retrieved and should not be called again on that thread. 
I'm thinking of the situation where this could fail:
Thread 1: sends a request and calls serve
Thread 2: sends a request and calls serve
Thread 2: gets thread 1s response, returns True, waits on `_is_ready.wait()`
Thread 1: fails for some reason, returns False
Thread 2: `_is_ready.set()` is never called

I'm not sure the solution. I think your PR (#463) might re-introduce the deadlock issue (#449) but I haven't tested it. I'll do more investigation tomorrow.

**Comment by wumb0** [comment]
Thinking on this overnight, can you try adding back the wait like this?
```python
            if self._conn.serve(self._ttl):
                # we received a response, wait for the completion call
                self._is_ready.wait(self._ttl.timeleft())
```
Adding the `timeleft` call should exit the wait properly in case it is never received. 
Does that fix your issue?

**Comment by achrafka** [comment]
i added the `timeleft` but the problem still remains and i think my solution might not re-introduce the deadlock issue as you see the problem is in the wait the call never exit and `_is_ready.set()` never called 

but i got another solution and it is to call `expired` so we can exit the wait properly
```
if self._conn.serve(self._ttl):
                self._is_ready.wait(self._ttl.expired())
```
what do you think ? it worked for me

**Comment by wumb0** [comment]
`expired` returns a `bool` so it doesn't make sense to do this.

**Comment by achrafka** [comment]
My bad so there is no way to exit the `wait()` func

**Comment by wumb0** [comment]
That is what pasing the return from timeleft would do. So if it doesn't
actually complete in the time it is expected to, then it breaks out of the
wait call and returns a failure (raises a timeout).
I'd need a minimal test case to help you debug further, as I can't
reproduce the issue with any code that I have.

**Comment by comrumino** [comment]
I skimmed the above conversation a bit. I retested the issue from #449 and there are not any regressions from my testing.
