### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by benjamin-kirkbride** [tomerfiliba-org/rpyc#473]
The most recent release was over a year ago, and lots of improvements have been made since then. I keep running into weird issues and just noticed that the `latest` docs are pretty different from what I'm actually using.

When can we expect a new release? I am loving RPyC so far, and am really looking forward to using these new features :)

**Comment by comrumino** [comment]
Thanks for the love! I'll work on getting a new release out soon. I suppose I should update the docs with a note about install from master like so `python -m pip install git+https://github.com/tomerfiliba-org/rpyc.git`. I'll keep ya updated!

**Comment by benjamin-kirkbride** [comment]
Great!

Unfortunately, installing like that doesn't work with things like setuptools, so that does work for local dev, but not for packaging :/

**Comment by comrumino** [comment]
5.1.0 is now available.

I think there are dependency links that can be used. Of course, for packages that RPyC is already a dependency that would not work. Anyway, I refined my notes on pushing a release so that it is less tedious and I'll try to be more proactive in doing releases.
