### ISSUE TITLE
References to service members or remote objects sometimes returns None? (flaky)

### ISSUE THREAD

**Issue by benjamin-kirkbride** [tomerfiliba-org/rpyc#475]
I'm using RPyC for testing a game I'm working on and am extremely impressed thus far. I am having an issue though, sometimes, inconsistently, objects are returning values of None when I inspect them, including methods of the Service. Why might this be?

Reproducing an example has proven really difficult, as again it's flaky. It seems to be one of those issues where when you add a bunch of logging it disappears..

I do have the RPyC server running in a separate thread from most of the stuff I'm inspecting (using the `SlaveService`), but I have set up logs to fire off prior to the inspection of these objects that say that they are not `None`, and that doesn't explain why exposed methods of the service also come up as `None` sometimes :thinking: 

Any help in troubleshooting this is greatly appreciated.

**Comment by benjamin-kirkbride** [comment]
Here is an example:

![image](https://user-images.githubusercontent.com/3373830/150923775-306c7afa-2276-4327-a04a-2be1b8f71a6a.png)

Note that the `key` method of the service copied below is seen as a `NoneType` on this run specifically, even though 9/10 times it is not.

```python
def service_factory(name: str):
    class ServantService(ServantServiceBase):
        ALIASES = [name]

        def click_button(self, button: str, frame: int = -1, priority: int = 0):
            request = RPCRequest(
                priority=priority,
                type="click_button",
                body=ClickButtonBody(frame=frame, button=button),
            )
            self.request_queue.put(request)

        def connect_to_server(
            self, address: str, port: int, frame: int = -1, priority: int = 0
        ):
            request = RPCRequest(
                priority=priority,
                type="connect_to_server",
                body=ConnectToServerBody(frame=frame, address=address, port=port),
            )
            self.request_queue.put(request)

        def key(
            self,
            key: Union[str, int],
            pressed: bool,
            frame: int = -1,
            priority: int = 0,
        ):
            if isinstance(key, str):
                key = KEYS[key]

            request = RPCRequest(
                priority=priority,
                type="key",
                body=KeyBody(frame=frame, pressed=pressed, key=key),
            )
            self.request_queue.put(request)

    return ServantService
```

here is the `ServantServiceBase` for posterity, though I don't think it makes a difference:

```
class ServantServiceBase(rpyc.core.service.SlaveService):
    ALIASES = ["Servant"]

    def __init__(self):
        super().__init__()

        self.request_queue = queue.PriorityQueue()
        self.response_queue = queue.Queue()

    def get_attribute(self, attribute_path: str) -> Any:
        """get an attribute of the RPC Handler in a thread-safe way

        args:
            attribute_path: period seperated string denoting path of attribute
                relative to Handler

        example `attribute_path`s:
            - `window.frame_count`
            - `window.current_view`
            - `server.tick_count`
        """
        request = RPCRequest(
            priority=0,
            type="get_attribute",
            body=GetAttributeBody(attribute_path=attribute_path),
        )
        self.request_queue.put(request)
        return self.response_queue.get(timeout=1)
```

**Comment by notEvil** [comment]
Hi,

on first glance I'd say the issue is not related to rpyc. Your `ServantServiceBase.get_attribute` assumes a temporal correlation between request and response which isn't there. Two threads may call `ServantServiceBase.get_attribute` at the same time and end up racing for the response at `response_queue.get`. And depending on the rest of the code, any request which creates a response (in your code and terminology) would interfere and break the correlation.

That said, `ServantServiceBase.get_attribute` is currently not thread-safe

**Comment by comrumino** [comment]
If it turns out you disagree w/ @notEvil feel free to reopen
