### ISSUE TITLE
Improve documentation and maybe support multiprocessing for RPyC

### ISSUE THREAD

**Issue by m0hithreddy** [tomerfiliba-org/rpyc#482]
I have a simple class that declares connection object from ``rpyc.connect(...)`` as a class instance. When I try to run a ``classmethod`` which uses the connection object parallelly in two processes I get some RPyC internal errors.

### Steps to Reproduce:

**Client:**

    import threading
    from multiprocessing import Process
    
    import rpyc
    
    if __name__ == '__main__':
        class Test:
            conn = rpyc.connect('localhost', 18813)
            lock = threading.Lock()
    
            @classmethod
            def run(cls):
                cls.lock.acquire()
                print('I acquired lock')
                print(cls.conn.root.remote_import('builtins').list([1, 2]))
    
    
        proc1 = Process(target=Test.run)
        proc2 = Process(target=Test.run)
    
        proc1.start()
        proc2.start()
    
        proc1.join()
        proc2.join()

**Server:**

    from importlib import import_module
    
    import rpyc
    
    
    class TestService(rpyc.Service):
    
        @classmethod
        def exposed_remote_import(cls, name, package=None):
            return import_module(name, package)
    
    
    if __name__ == '__main__':
        s = rpyc.ThreadedServer(
            service=TestService, hostname='localhost', port=18813,
            protocol_config={
                'allow_all_attrs': True
            }
        )
        s.start()

### Results:

**Expected:**
I expect RPyC to return ``NetRef`` of the ``[1, 2]`` in both the processes.

**Actual:**
I get a range of exceptions from RPyC internal classes.

### StackTrace:

**Variant 1:**

    I acquired lock
    I acquired lock
    (***HANGS***)

**Variant 2:**

    I acquired lock
    I acquired lock
    Process Process-2:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
        self.run()
      File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
        self._target(*self._args, **self._kwargs)
      File "/tmp/scratches/scratch_1.py", line 15, in run
        print(cls.conn.root.remote_import('builtins').list([1, 2]))
      File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 507, in root
        self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
      File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 474, in sync_request
        return self.async_request(handler, *args, timeout=timeout).value
      File "/usr/lib/python3.7/site-packages/rpyc/core/async_.py", line 101, in value
        self.wait()
      File "/usr/lib/python3.7/site-packages/rpyc/core/async_.py", line 48, in wait
        self._conn.serve(self._ttl)
      File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 397, in serve
        self._dispatch(data)
      File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 360, in _dispatch
        msg, seq, args = brine.load(data)
    ValueError: too many values to unpack (expected 3)

**Variant 3:**

    I acquired lock
    I acquired lock
    Process Process-2:
    Traceback (most recent call last):
      File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
        self.run()
      File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
        self._target(*self._args, **self._kwargs)
      File "/tmp/scratches/scratch_1.py", line 15, in run
        print(cls.conn.root.remote_import('builtins').list([1, 2]))
      File "/usr/lib/python3.7/site-packages/rpyc/core/netref.py", line 240, in __call__
        return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
      File "/usr/lib/python3.7/site-packages/rpyc/core/netref.py", line 63, in syncreq
        return conn.sync_request(handler, proxy, *args)
      File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 474, in sync_request
        return self.async_request(handler, *args, timeout=timeout).value
      File "/usr/lib/python3.7/site-packages/rpyc/core/async_.py", line 101, in value
        self.wait()
      File "/usr/lib/python3.7/site-packages/rpyc/core/async_.py", line 48, in wait
        self._conn.serve(self._ttl)
      File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 397, in serve
        self._dispatch(data)
      File "/usr/lib/python3.7/site-packages/rpyc/core/protocol.py", line 360, in _dispatch
        msg, seq, args = brine.load(data)
    TypeError: cannot unpack non-iterable NoneType object

**----And Others-----**

I am tempted to say that the connection objects of the two processes are not independent like the ``lock`` objects.

### Environment

- RPyC Version: 5.1.0
- Python Version: 3.7.12
- Operating System: Linux (Ubuntu 20.10)

**Comment by m0hithreddy** [comment]
### Working Clients:

**Client1:**

    import multiprocessing
    import threading
    from multiprocessing import Process
    
    import rpyc
    
    
    class Test:
        conn = rpyc.connect('localhost', 18813)
        lock = threading.Lock()
    
        @classmethod
        def run(cls):
            cls.lock.acquire()
            print('I acquired lock')
            print(cls.conn.root.remote_import('builtins').list([1, 2]))
    
    
    if __name__ == '__main__':
        multiprocessing.set_start_method('spawn')
    
        proc1 = Process(target=Test.run)
        proc2 = Process(target=Test.run)
    
        proc1.start()
        proc2.start()
    
        proc1.join()
        proc2.join()

**Client2:**

    import threading
    from multiprocessing import Process, Lock
    
    import rpyc
    
    if __name__ == '__main__':
        glb_lock = Lock()
    
        class Test:
            conn = rpyc.connect('localhost', 18813)
            lock = threading.Lock()
    
            @classmethod
            def run(cls):
                with glb_lock:
                    cls.lock.acquire()
                    print('I acquired lock')
                    print(cls.conn.root.remote_import('builtins').list([1, 2]))
    
    
        proc1 = Process(target=Test.run)
        proc2 = Process(target=Test.run)
    
        proc1.start()
        proc2.start()
    
        proc1.join()
        proc2.join()

I am assuming RPyC is not built to deal with multiple processes sharing the same connection (socket) object. It would be great
if this scenario can be dealt with. For now, I am picking the first approach as it creates a new connection object rather than using a shared one.

**Comment by comrumino** [comment]
Tracking this in #354 and closing here to cleanup issue backlog
