### ISSUE TITLE
Backwards incompatibility: signature changes in redirect_stdin and connect_by_service in 5.1.0

### ISSUE THREAD

**Issue by eXceediDeaL** [tomerfiliba-org/rpyc#488]
Hello, I found that the most recent version **5.1.0** of rpyc probably introduces some **breaking changes**, which are not recorded in release notes.

1. Remove optional parameter `redirect_stdin` from the function `rpyc.utils.classic.redirected_stdio`.
2. Add optional positional parameter `registrar`, `timeout` in the middle of `rpyc.utils.factory.connect_by_service` parameter list.

##### Environment

- rpyc version: 5.1.0
- python version: 3.7
- operating system: Ubuntu 18.04

##### Minimal example

The following code runs well in 5.0.1 but gets crashed in 5.1.0 because of the first change.

Server:

```sh
python rpyc_classic.py
```

Client:

```python
import rpyc
from rpyc.utils.classic import redirected_stdio

conn = rpyc.classic.connect("localhost")
with redirected_stdio(conn, False):
    pass
```

Error in rpyc 5.1.0:

```
Traceback (most recent call last):
  File "b.py", line 6, in <module>
    with redirected_stdio(conn, False):
TypeError: redirected_stdio() takes 1 positional argument but 2 were given
```

The second change would cause crash if calling `connect_by_service` with all positional arguments, e.g.

```python
connect_by_service(service_name, None, VoidService, {})
```

In this case running on rpyc 5.1.0, `registrar` parameter will accept `VoidService` and `timeout` paramter will accept `{}`.

Maybe recording these changes in release notes helps to avoid user confusion during updating this version?

Kind regrads,

@eXceediDeaL

**Comment by comrumino** [comment]
5.2.1 Release resolves this. See #500
