### ISSUE TITLE
Wheels on PyPI contain different code than is in this repository

### ISSUE THREAD

**Issue by gschaffner** [tomerfiliba-org/rpyc#500]
The wheels uploaded to PyPI for versions 5.0.1 and 5.1.0 contain different code than the corresponding v5.0.1 and v5.1.0 git tags.

tag = 5.1.0:
```diff
$ diff --color=always -r rpyc/rpyc/core/protocol.py dist/rpyc-5.1.0-py3-none-any.whl.d/rpyc/core/protocol.py
360a361
>         time.sleep(0.0)
```

tag = 5.0.1:
```diff
$ diff --color=always -r rpyc/rpyc/utils/classic.py dist/rpyc-5.0.1-py3-none-any.whl.d/rpyc/utils/classic.py
314c314
< def redirected_stdio(conn):
---
> def redirected_stdio(conn, redirect_stdin=True):
329c329,330
<         conn.modules.sys.stdin = sys.stdin
---
>         if redirect_stdin:
>             conn.modules.sys.stdin = sys.stdin
diff -r '--color=always' rpyc/rpyc/utils/teleportation.py dist/rpyc-5.0.1-py3-none-any.whl.d/rpyc/utils/teleportation.py
61a62
> 
```

I have not checked versions below 5.0.0. They may have similar issues.

`setuptools_scm` can prevent this type of issue as the resulting wheels will clearly identify themselves as development versions if they differ from what is checked in and tagged. Hatchling with `hatch-vcs` is a step better even, as the wheels and sdists produced by Hatchling are fully reproducible so users can easily check for supply-chain attacks. It's worth noting that Hatchling is the packaging.python.org recommendation now, and that Plumbum looks to be switching to Hatchling.

Regarding the 5.1.0 diff in particular, my guess is that it was inserted when testing #449. It causes a timeout bug for `ThreadedServer`s that looks a lot like #354. For example, with RPyC at tags 5.0.1 and 5.1.0, testing of https://github.com/tomerfiliba-org/rpyc/issues/477#issuecomment-1174581443 indicates that it closes its issue, but with RPyC at PyPI 5.1.0 this is not the case—the callbacks instead sometimes hit `sync_request_timeout`.

**Comment by comrumino** [comment]
That seems to be a careless mistake on my end. I will have to give `hatch-vcs` a try the next time I do a release. But also, I need to rewrite my release steps for release to PyPi to use a clean environment. This is something that is done for `PKGBUILD` releases by Arch Linux and likewise for other linux distros. Sorry!

**Comment by comrumino** [comment]
Updated the [release process](https://rpyc.readthedocs.io/en/latest/docs/rpyc-release-process.html?highlight=release)

**Comment by gschaffner** [comment]
Awesome, thanks for the work you do for this project! I am happy that there is build reproducibility via hatchling now :)
