### ISSUE TITLE
rpyc_classic.py: No such file or directory (RPyC 5.2.1)

### ISSUE THREAD

**Issue by odiassli** [tomerfiliba-org/rpyc#503]
After installing rpyc 5.2.1 - I see that rpyc_classic.py: No such file or directory
downgrade to 5.1.0 - rpyc_classic.py exists and works good
##### Environment

- rpyc version: rpyc 5.2.1
- python version: Python3.8
- operating system: QNX 7

Repro: python bin/rpyc_classic.py

**Comment by comrumino** [comment]
I'm sure I missed it when I switched to using `pyproject.toml`. I'll take a look in a bit

**Comment by comrumino** [comment]
5.2.3 release resolves this issue. Thanks for bringing it to my attention!
