### ISSUE TITLE
Automatic reconnection

### ISSUE THREAD

**Issue by jacobfeder** [tomerfiliba-org/rpyc#508]
Is there an obvious way to support automatic reconnection e.g. if the server connection goes down but then is brought back up? I have implemented a wrapper for the rpyc client with the following:

```
  def connect(self):
        try:
            self._connection = rpyc.connect(
                self.addr,
                self.port,
                config={
                    'allow_pickle': True,
                    'timeout': RPYC_CONN_TIMEOUT,
                    'sync_request_timeout': self.sync_timeout,
                },
            )
        ...

    def reconnect(self):
        self.disconnect()
        self.connect()

    def __getattr__(self, attr: str):
        if self._connection:
            try:
                return getattr(self._connection.root, attr)
            except EOFError:
                # the server might have disconnected - try reconnecting
                self.reconnect()
                return getattr(self._connection.root, attr)
        else:
            # raise the default python error when an attribute isn't found
            return self.__getattribute__(attr)

```

This works reasonably well, but the problem is the client side may have dangling netrefs whose pipes/sockets will not properly reconnect, even when the client wrapper does reconnect.

**Comment by comrumino** [comment]
I think trying to handle reconnection in the same scope as your netrefs will make dangling netrefs hard to manage. Even so, you can check if they are dangling via `getattr(netref, '____conn__').closed`. You might want to consider managing the reconnection one frame up from where your netrefs are managed-this would let you simply GC them and not have to manually check connection state.
