### ISSUE TITLE
Question: passing complicated values by value from server to client?

### ISSUE THREAD

**Issue by sidneycadot** [tomerfiliba-org/rpyc#510]
I need to pass a non-trivial value from a server to a client (such as a Python dict or a list). However, on the client-side, I will receive a netref by default for such values.

One way to achieve this is calling rpyc.utils.classic.obtain() on the client-side. However, this has two downsides. First, pickling needs to be enabled for the server. And second, this places the decision solely on the side of the client, whereas the server may want to decouple its local value from the remote side as a matter of policy (i.e. always do a pass-by-value rather than a pass-by-netref); and it may want to do this without explicitly enabling client-initiated pickling requests.

Is there a way to achieve this behavior?

If not, I'd like to mark this as a feature request; i.e. a way for the server to return a value that, at the client side, will also be represented as a value, rather than a netref.

**Comment by sidneycadot** [comment]
I think this is more-or-less a duplicate of issue #350 and (especially) the closed #310.

Given that those issues are quite old, I fear that there will be no action anytime soon on this. Hence my question -- suppose I dive in and come up with a solution, will a pull request that addresses this issue be considered for inclusion?

**Comment by sidneycadot** [comment]
Also related: issue #393.

**Comment by comrumino** [comment]
Agreed. #393 was a dup of #350 and so is this issue. While RPyC aims to be transparent, "unexpected" behavior from CPython seems to be a consistent pain point. 

Of course, documentation and making RPyC easy to use are important. So, I always welcome PRs!
