### ISSUE TITLE
Module description is strange when using VS Code

### ISSUE THREAD

**Issue by rafrafek** [tomerfiliba-org/rpyc#512]
Module description looks strange when using VS Code:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/23004737/198028981-e25aefbe-7279-430b-b478-9dc51e7bf0a7.png">

I'm not sure if it's a VS Code or a RPyC bug.

**Comment by rafrafek** [comment]
Submitted also here: https://github.com/microsoft/vscode/issues/164709

**Comment by comrumino** [comment]
Closing this issue after commenting on upstream. It seems VS Code struggles w/ RST.
