### ISSUE TITLE
A difference between rpyc 3.3.0 and 5.1.0

### ISSUE THREAD

**Issue by SeaBradley198** [tomerfiliba-org/rpyc#514]
Hi, I am trying to reconcile a difference between rpyc 3.3.0 and rpyc 5.1.0 involving a timeout for commands. Does 3.3.0 have a timeout similar to the one in 5.1.0 ( 'sync_request_timeout')? If not, then is there any timeout at all on commands for 3.3.0?

**Comment by comrumino** [comment]
RPyC introduced `sync_request_timeout` in `v3.4.0`. The merge 14d88ad added timeout support after `v3.3.0` was released. In short, there is not. You'd need to use `v3.4.0`.
