### ISSUE TITLE
Question: How to override _rpyc_getattr but also fall back to default attribute access?

### ISSUE THREAD

**Issue by mvashishtha** [tomerfiliba-org/rpyc#523]
My rpyc service exposes an object with an attribute called `_summary`. I want users at the client side to get this object using this exact attribute name, but it's not allowed by the default rpyc attribute protection rules (presumably because of the single leading underscore). I see from the [documentation](https://rpyc.readthedocs.io/en/latest/docs/security.html#attribute-access) that I can allow access to a custom attribute by overriding `_rpyc_getattr`. I tried writing this:

```python
def _rpyc_getattr(self, name):
    if name.startswith("_") and name != "_summary":
        raise AttributeError(f"cannot access {name}")
    # allow all other attributes
    return getattr(self, name)
```

but that disallowed dunder methods like `__len__`, which I also need to expose. I could explicitly allow the dunder methods I need, but that would complicate my code.

Is there some way to check whether `name` is the special attribute `_summary` and get it if so, but otherwise fall back to the default rpyc attribute access? I can't find the existing `_rpyc_getattr` implementation, so I can't copy that either.

**Comment by comrumino** [comment]
The default accessor for RPyC is `getattr`. `_check_attr` should cover the dunder methods in it. The issue has more to do with not using the exposed prefix (default is `exposed_prefix="exposed_"`). Attribute access can be a little tricky, I'd recommend checking out the unit tests `test_attr_access.py`. I'd recommend keeping it simple.
