### ISSUE TITLE
Detect remote `rpyc` version

### ISSUE THREAD

**Issue by ajmeese7** [tomerfiliba-org/rpyc#529]
Is there a way to detect the version of `rpyc` running on the remote side to determine if it is compatible with the locally running version?

**Comment by comrumino** [comment]
Yes. I try to follow semantic versioning. So, adding a function to your service to return the major version would work. 
```
>>> local_major_version = rpyc.version.version[0]
>>> conn.get_major_version() == local_major_version
```
There may be room to improve RPyC's usability here. Let me know if that helps.

**Comment by comrumino** [comment]
I'm going close this out, feel free to reopen if you have related questions.
