### ISSUE TITLE
Can methods exposed with the @rpyc.exposed decorator have an alias?

### ISSUE THREAD

**Issue by stautonico** [tomerfiliba-org/rpyc#533]
I would like to expose a method in my service class, but give it an alias

For example

```py
# server
class MyService(rpyc.Service):
    @rpyc.exposed
    def prefix_myfunction(self):
        return "myfunction called!'
```

To call this function using the RPC client, we have to do

```py
# client
client = rpyc.connect("localhost", 5002)

client.root.prefix_myfunction()
```

I would like to be able to leave the prefix out:

```py
# client
client = rpyc.connect("localhost", 5002)

client.root.myfunction()
```

Is there any way to give an alias to an exposed function with the decorator?

I couldn't find anything in the documentation.

Thanks

**Comment by comrumino** [comment]
The default behavior is to use the prefix `exposed_`. Try passing the `prefix_` to your decorator like below and you should be able to call both `prefix_myfunction` and `myfunction`.
```
class MyService(rpyc.Service):
    @rpyc.exposed('prefix_')
    def prefix_myfunction(self):
        return "myfunction called!'
```

[The custom service unit tests shows the behavior you are looking for.](https://github.com/tomerfiliba-org/rpyc/blob/master/tests/test_custom_service.py#L123-L124)
