### ISSUE TITLE
pyproject.toml value for license key should be a table, not a string

### ISSUE THREAD

**Issue by DavidAntliff** [tomerfiliba-org/rpyc#536]
Please refer: https://github.com/tomerfiliba-org/rpyc/blob/5f41958d19cb4ca813ed1c289f7496faf849c7bf/pyproject.toml#L11

According to the [Packaging Metadata docs](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#license), the `project.license` field should be a table, not a string:

E.g.
```
license = {text = "MIT License"}
```

This is currently preventing RPyC being installed with Yocto 4.1: 

```
| ValueError: invalid pyproject.toml config: `project.license`.
| configuration error: `project.license` must be valid exactly by one definition (2 matches found):
| 
|     - keys:
|         'file': {type: string}
|       required: ['file']
|     - keys:
|         'text': {type: string}
|       required: ['text']
| 
| ERROR: 'python3 setup.py bdist_wheel ' execution failed.
```

**Comment by comrumino** [comment]
ty resolved per your recommendation
