### ISSUE TITLE
Specify a point of contact for security-related issues

### ISSUE THREAD

**Issue by renbou** [tomerfiliba-org/rpyc#551]
Hi! I wasn't able to find any information regarding how and where security issues should be reported. I have sent a report via Snyk, however, it will take them a while to verify it, which is why I've decided to create an issue here. If there isn't a publicly available point of contact, please contact me via the email address specified in my profile.

If it is more comfortable for you to have the problem disclosed publicly in this issue, then I'd be glad to just share all the details here.

**Comment by comrumino** [comment]
Feel free to email me `j.a.stronz@gmail.com`
